# Generated by Django 5.0.6 on 2024-06-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default_cover.png', null=True, upload_to='static/images'),
        ),
    ]
