# Generated by Django 5.0.6 on 2024-06-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
