# Generated by Django 5.0.6 on 2024-06-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('choosing', 'В корзине'), ('pending', 'В ожидании'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='choosing', max_length=20),
        ),
    ]
