# Generated by Django 5.0.6 on 2024-06-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/default_cover.png', upload_to='product_images/'),
        ),
    ]
